### ISSUE TITLE
Project and class enrichers

### ISSUE THREAD

**Issue by Zerogiven** [klitsche/dog#2]
First, thanks for a doc generator which uses simple and known techniques like twig(and other symfony components) and an easy understandable printer system ;)

However, one feature i really love is from phpDox called Enrichers. Not sure if you know about it, but in short it enriches project and/or class property with additional informations.

I think such enrichers could make your dog to a killer dog ;D

The enrichers should enrich the $project property before giving it to the printer. So the printer can handle the enrichments for example inside twig template.

I think one easy example to start would be enrich $project with phpLoc informations :)

To make it more easier: https://github.com/phpexpertsinc/PHPLOCAnalyzer produces an array of lines-of-code informations for a given path. (not sure if it handles multiple paths, but this could be merged easy).

A second example (which would be more interesting for me) is to enrich classes and/or methods with phpunit informations given by an generated xml.

With such enrichers you can show inside twig templates which method is test covered, or show the phploc informations on the index page,... Of course there are many more possibilities :)

What i really dislike from phpDox is that i did not found an (easy!) way to make custom enrichers and their templates are made with xsl........

At the moment i am making a custom html printer for _dog_, without mkdocs, but with some custom printer configs like using a readme file as index page, custom template path,... But if you agree that this enhancement is a good idea and make anytime such an "Enricher System", i would love to make some of the enrichers ;)

cheers

**Comment by dirx** [comment]
hi @Zerogiven, thanks for the 💐. I like the enricher idea.

Some rough first thoughts:

- Enricher should be configurable (like printer)
- Enricher should be classes holding own logic to map their data to Project and Elements
- Enricher should implement some generic Enricher Interface
- Dog should init each Enricher upfront before scanning the project (like reading and holding the phploc json file that was generated by another process before) 
- After creating Project and Elements Enricher will visit Project and all Elements to add data
- Project and Elements should implement some generic extra data getter / setter interface and holding extra data

Not sure about if Enricher should map and add data directly or attach themselves to Project and Elements and map and return data later on demand (eg. during printing). 

What do you think?

**Comment by dirx** [comment]
Hi @Zerogiven, I added generic support for enrichers plus basic examples for phploc json and clover xml files. 

I went for the generic data adding way. Enrichers could instead of data also add themselves so you may access them later on during printing. Enrichers could even take care of additional information like "implemented / extended / used by" or provide "source code" snippets.

Would be great if you could take a look and play around to find out how this works for your and if you experience any glitches.

Plus: feel free to contribute printers & enrichers and improvements.

**Comment by Zerogiven** [comment]
Hi @dirx first wanna say thanks for your fast implementation :D

I am a bit busy at the moment cause i'm painting my apartment but i'll take a look next days for sure! But it already sounds very good and interesting :))

cheers

**Comment by Zerogiven** [comment]
Tried my first experiments this weekend and i am very excited :)) 👍 

At the moment i "just" use your enrichers for extending my html template but i am heavily inspired to make some more :))

And a simple method where you can get an array of which enrichers are used by the project would be handy i think ^_^

**Comment by dirx** [comment]
What would be the use case for this method?

**Comment by Zerogiven** [comment]
Oh sorry i forgot to give an answer at this point: I already figured it out ;D

However, i finished the html printer, maybe you can take a look at it and/or link it in your readme or gh-pages ;)

https://github.com/CSoellinger/dog-html-printer

Generated example docs:
https://csoellinger.github.io/dog-html-printer/html/

i close this thread :)
